PresentationLayer/HRIS.MvcApp/Controllers/SiteMasterController.cs
using HRIS.Data.MasterData;
using HRIS.Data.UserData;
using HRIS.MvcApp.Core;
using HRIS.MvcApp.Filters;
using HRIS.MvcApp.HRISService;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace HRIS.MvcApp.Controllers
{
    public class SiteMasterController : BaseController
    {
        private IHRISService ServiceClient = ServiceHelper.GetHRISService();

        [CustAuthFilter]
        public ActionResult Index()
        {
            return View();
        }

        [CustAuthFilter]
        public ActionResult GetSiteDataList()
        {
            var siteList = ServiceClient.GetSiteDataList("","");
            var jsonResult = Json(siteList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }

        
        [CustAuthFilter]
        public ActionResult SaveSiteSubSiteMapping(List<SiteSubSiteMappingData> model)
        {
            var result = ServiceClient.SaveSiteSubSiteMapping(model.ToArray());
            return Json(result, JsonRequestBehavior.AllowGet);
        }

    }
}

PresentationLayer/HRIS.MvcApp/Views/SiteMaster/Index.cshtml
<script>

    var HRISMasters = {
        GetLoginUserDetailsUrl: "@Url.Action("GetLoginUserDetails", "CookBookMaster")",
        GetSiteDataList: "@Url.Action("GetSiteDataList", "SiteMaster")",
        SaveSiteSubSiteMapping: "@Url.Action("SaveSiteSubSiteMapping", "SiteMaster")"
    }
</script>

<script src="~/Scripts/CookBook/Site.js"></script>
<link href="~/Content/css/styles.css" rel="stylesheet" />
<style>
#gridBulkChange .k-input {text-align:left}
    .slider {
        top: 6px !important;
        bottom: -6px !important;
    }
    .k-window-titlebar {
        font-weight:400;
    }

    .k-dropdown {
        width: 107% !important;
    }

    .gridDiv .upper {
        background-color: rgb(118,180,176);
        padding: 5px;
        border-radius: 5px 5px 0 0;
        padding-left: 10px !important;
        height: 35px;
        color: white;
        cursor: pointer;
    }
</style>
@{
    ViewBag.Title = "Location Splitting";
}

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <section class="col-sm-12 connectedSortable" style="display:inherit; min-height:480px">
                <div id="SiteMaster" class="col-lg-12 card direct-chat direct-chat-primary">
                    <div class="card-header">
                        <h3 class="card-title" style="margin-left: -17px;">Location Splitting Details</h3>
                        <div class="card-tools" style="margin-top: -6px;">
                            <span style="float:left; margin-top:2px!important">
                                <input type="text" id="myInput" placeholder="Search" class="search-input" title="Start typing to filter">
                                <i class="fas fa-search" style="    position: relative; right: -277px;top: 4px;font-size: 0.7em;color: #76b4b0;"></i>
                            </span>
                            <button id="btnExport" type="submit" class="btn btn-tool" data-toggle="tooltip" title=""
                                    data-widget="chat-pane-toggle" style="padding-top:7px">
                                Export To Excel
                            </button>
                        </div>
                    </div>
                    <div id="siteid" style="display:none;"></div>
                    <!-- /.card-header -->
                    <div id="fpbody" class="card-body">
                        <div id="bulkerror" class="alert alert-danger alert-dismissible" style="display:none">
                            <i class="icon fas fa-exclamation"></i>
                            <p style="font-size: 12px;margin-bottom: .15rem;margin-left: 5px;">
                            </p>
                        </div>
                        <div id="success" class="alert alert-success alert-dismissible" style="display:none">
                            <i class="icon fas fa-check"></i>
                            <p style="font-size: 12px;margin-bottom: .15rem;margin-left: 5px;">
                            </p>
                        </div>
                        <div id="gridSite"></div>
                        <div id="OtherEditwindowEdit" style="display:none;">
                            <div class="container" style="padding:15px!important;">
                                <div id="error" class="alert alert-danger alert-dismissible" style="display:none">
                                    <i class="icon fas fa-exclamation"></i>
                                    <p style="font-size: 12px;margin-bottom: .15rem;margin-left: 5px;">
                                    </p>
                                </div>

                                <div class="row">
                                    <div class="col-12">
                                        <div class="dishRecipe">
                                            <div class="upper" style="height: 24px;" id="mup_gridSubSiteMapping">
                                                Location Spliiter

                                                <br />

                                            </div>
                                            <div class="lower">
                                                <div id="gridSubSiteMapping"></div>
                                            </div>
                                          </div>
                                        </div>
                                        @*<div class="col-4">
                                            <label class="form-control-label">Number of Sub Site <span class="mandatoryAsterisk">*</span></label>
                                            <input type="text" id="NumberOfSubSite" class="form-control" />
                                        </div>
                                        <div class="col-7" style="margin-top: 13px;">
                                            <button type="submit" id="SubSiteGo" class="btn btn-info">Go</button>
                                        </div>*@


                                    </div>

                                    <div class="row" style="margin-top: 15px !important; margin-right: 0px !important;margin-bottom:0px;">
                                        <div class="modal-footer col" style="padding-right:0px!important;right:7px; align-items:flex-end!important">
                                            <button type="submit" id="OthSMbtnCancel" class="btn btn-tool">Cancel</button>
                                            <button type="submit" id="OthSMbtnSubmit" class="btn btn-info">Save</button>
                                        </div>
                                    </div>
                                </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
         
                    <!-- /.card-footer-->
                </div>
            </section>
            <!-- /.Left col -->
        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>