PresentationLayer/HRIS.MvcApp/Controllers/HRISMasterController.cs
using ClosedXML.Excel;
using HRIS.Aspects.Factory;
using HRIS.Data;
using HRIS.Data.Request;
using HRIS.Data.UserData;
using HRIS.MvcApp.Core;
using HRIS.MvcApp.Filters;
using HRIS.MvcApp.HRISService;
using HRIS.MvcApp.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data;
using System.DirectoryServices;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
//using System.Web.Script.Serialization;
using HRIS.Data.MasterData;
using HRIS.Encryption.EncryptImpl;
using System.Reflection;
using Newtonsoft.Json;
using System.Globalization;
using System.Runtime.CompilerServices;
using HRIS.Encryption.Interfaces;

namespace HRIS.MvcApp.Controllers
{
    public class HRISMasterController : BaseController
    {
        private IHRISService ServiceClient = ServiceHelper.GetHRISService();

        [CustAuthFilter]
        public ActionResult Index()
        {
            return View();
        }

        [CustAuthFilter]
        public ActionResult GetLoginUserDetails()
        {
            //string UserName = User.Identity.Name;
            //string uname = "";
            //if (UserName.IndexOf("\\") > 0)
            //{
            //    uname = UserName.Split('\\')[1];
            //}
            //else
            //{
            //    uname = UserName;
            //}
            //if (string.IsNullOrEmpty(uname) && !string.IsNullOrEmpty(ConfigurationManager.AppSettings[Constants.TEST_USER]))
            //{
            //    uname = ConfigurationManager.AppSettings[Constants.TEST_USER];
            //}
            var res = Session["UserLoginDetails"];


            return Json(res, JsonRequestBehavior.AllowGet);
        }

        [CustAuthFilter]
        public ActionResult ProfitCenter()
        {
            return View();
        }

        [CustAuthFilter]
        public ActionResult SaveProfitCenterData(ProfitCenterMasterData model)
        {
            UserMasterResponseData userData = (UserMasterResponseData)Session["UserLoginDetails"];

            if (model.ID == 0)
            {
                model.CreatedBy = userData.UserId;
                model.CreatedOn = DateTime.Now;
            }
            else
            {
                model.ModifiedBy = userData.UserId;
                model.ModifiedOn = DateTime.Now;
            }
            var result = ServiceClient.SaveProfitCenterDataList(model);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [CustAuthFilter]
        public ActionResult CostCenter()
        {
            return View();
        }


        [CustAuthFilter]
        public ActionResult SaveCostCenterData(CostCenterMasterData model)
        {
            UserMasterResponseData userData = (UserMasterResponseData)Session["UserLoginDetails"];

            if (model.ID == 0)
            {
                model.CreatedBy = userData.UserId;
                model.CreatedOn = DateTime.Now;
            }
            else
            {
                model.ModifiedBy = userData.UserId;
                model.ModifiedOn = DateTime.Now;
            }
            var result = ServiceClient.SaveCostCenterDataList(model);
            return Json(result, JsonRequestBehavior.AllowGet);
        }


        [CustAuthFilter]
        public ActionResult ITILiteMaster()
        {
            return View();
        }

        [CustAuthFilter]
        public ActionResult SaveLeaderShipRoleData(LeaderShipRoleMasterData model)
        {
            UserMasterResponseData userData = (UserMasterResponseData)Session["UserLoginDetails"];

            if (model.ID == 0)
            {
                model.CreatedBy = userData.UserId;
                model.CreatedOn = DateTime.Now;
            }
            else
            {
                model.ModifiedBy = userData.UserId;
                model.ModifiedOn = DateTime.Now;
            }
            var result = ServiceClient.SaveLeaderShipRoleDataList(model);
            return Json(result, JsonRequestBehavior.AllowGet);
        }


        [CustAuthFilter]
        public ActionResult LeaderShipRole()
        {
            return View();
        }
        [CustAuthFilter]
        public ActionResult LocationDesignation()
        {
            return View();
        }
        [CustAuthFilter]
        public ActionResult GetLocationDesignationMappingDataList()
        {
            // UserMasterResponseData userData = (UserMasterResponseData)Session["UserLoginDetails"];
            var leaderShipRoleList = ServiceClient.GetLocationDesignationMappingDataList();
            var jsonResult = Json(leaderShipRoleList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }
        [CustAuthFilter]
        public ActionResult GetUniqueLocationAndDesignationData()
        {
            // UserMasterResponseData userData = (UserMasterResponseData)Session["UserLoginDetails"];
            var leaderShipRoleList = ServiceClient.GetUniqueLocationAndDesignationDataList();
            var jsonResult = Json(leaderShipRoleList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }
        [CustAuthFilter]
        public ActionResult SaveLocationDesignationData(string location, string designation)
        {

            var result = ServiceClient.SaveLocationDesignationData(location, designation);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [CustAuthFilter]
        public ActionResult ConsultantDataUploader()
        {
            return View();
        }
        [CustAuthFilter]
        public ActionResult DiceUploader()
        {
            return View();
        }

        [CustAuthFilter]
        public ActionResult LensUploader()
        {
            return View();
        }
        //[HttpGet]

        [CustAuthFilter]
        public ActionResult DownloadExcTemplateCDU(string template)
        {
            //var mogList = ServiceClient.GetNOTMappedMOGDataList(GetRequestData());
            DataTable dt = new DataTable();
            string name = "", filename = "";
            //if (template == "Group")
            //{
            //    dt.Columns.Add("EmployeeCode");
            //    dt.Columns.Add("EmployeeName");
            //    dt.Columns.Add("GroupYesNo");
            //    name = "GroupUploader";
            //    filename = "GroupUploader";
            //}
            if (template == "Cost Center")
            {
                dt.Columns.Add("EmployeeCode");
                dt.Columns.Add("CostCenterCode");
                dt.Columns.Add("ProfitCenterCode");
                dt.Columns.Add("CostCenterRemarks");
                dt.Columns.Add("ProfitCenterRemarks");
                name = "CostCenterUploader";
                filename = "CostCenterUploader";
            }
            else if (template == "Map4")
            {
                dt.Columns.Add("EmployeeCode");
                dt.Columns.Add("EmployeeName");
                dt.Columns.Add("Division");
                dt.Columns.Add("TEPortalUserYesNo");
                name = "Map4Uploader";
                filename = "Map4Uploader";
            }
            else if (template == "Consultant")
            {
                dt.Columns.Add("EmployeeCode");
                dt.Columns.Add("EmployeeName");
                dt.Columns.Add("FirstName");
                dt.Columns.Add("LastName");
                dt.Columns.Add("Gender");
                dt.Columns.Add("DateOfBirth");
                dt.Columns.Add("Department");
                dt.Columns.Add("HRISSector");
                dt.Columns.Add("Grade");
                dt.Columns.Add("Designation");
                dt.Columns.Add("Company");
                dt.Columns.Add("ProfitCenter");
                dt.Columns.Add("CostCenter");
                dt.Columns.Add("OfficeEmailAddress");
                dt.Columns.Add("Location");
                dt.Columns.Add("State");
                dt.Columns.Add("MobileNumber");
                dt.Columns.Add("L1ManagerCode");
                dt.Columns.Add("L1Manager");
                dt.Columns.Add("L2ManagerCode");
                dt.Columns.Add("L2Manager");
                dt.Columns.Add("TEPortalUserYesNo");
                dt.Columns.Add("GroupEmployeeYesNo");
                dt.Columns.Add("ConstultantEmployeeYesNo");
                dt.Columns.Add("ExeComEmpCode");
                dt.Columns.Add("ExeComEmpName");
                dt.Columns.Add("CFOEmpCode");
                dt.Columns.Add("CFOEmpName");
                name = "ConsultantUploader";
                filename = "ConsultantUploader";
            }
            //dt.Columns.Add("Alias");
            //dt.Columns.Add("ArticleNumber");
            //foreach (MOGNotMapped p in mogList)
            //{
            //    dt.Rows.Add(p.MOGCode, p.Name, p.Alias, p.ArticalNumber);
            //}
            using (XLWorkbook wb = new XLWorkbook())
            {
                dt.TableName = name + ".xlsx";
                wb.Worksheets.Add(dt);

                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", filename + ".xlsx");
                }
            }
        }


        [CustAuthFilter]
        [HttpPost]
        public string UploadExcelsheet()
        {
            string Res = string.Empty;
            DataTable dt = new DataTable();
            UserMasterResponseData userData = (UserMasterResponseData)Session["UserLoginDetails"];
            int username = userData.UserId;

            if (Request.Files.Count > 0)
            {
                var template = Request.Params["template"];
                var file = Request.Files[0];

PresentationLayer/HRIS.MvcApp/Views/HRISMaster/ConsultantDataUploader.cshtml
<script>

    var HRISMasters = {
        GetLoginUserDetailsUrl: "@Url.Action("GetLoginUserDetails", "HRISMaster")",
        UploadExcelsheet: "@Url.Action("UploadExcelsheet", "HRISMaster")",
        GetConsultantUploaderHISTORY: "@Url.Action("GetConsultantUploaderHISTORY", "HRISMaster")",
        GetConsultantUploaderData: "@Url.Action("GetConsultantUploaderData", "HRISMaster")",
        GetConsultantUploaderHISTORYByBatch: "@Url.Action("GetConsultantUploaderHISTORYByBatch", "HRISMaster")",
        baseurl:"@System.Configuration.ConfigurationManager.AppSettings["ApplicationUrl"]"
    }
</script>
<script src="~/Scripts/CookBook/ConsultantDataUploader.js"></script>
<style>
    .popover {
        z-index: 120000 !important;
    }

    .k-window {
        height: 140px !important;
    }

    .slider {
        top: 6px !important;
        bottom: -6px !important;
    }

    .direct-chat .card-body {
        overflow-x: initial !important;
    }

    .form-label-consultant-uploader {
        /*display: block !important;*/
        width: 100% !important;
        padding-bottom: 0.075px !important;
        margin-bottom: 0 !important;
        color: #a0a6ab !important;
        background-color: transparent !important;
        border: solid transparent !important;
        border-width: 1px 0 !important;
        font-weight: 400 !important;
    }

    #GETALLPmViewALLHistoryBATCHWISE .k-grid-content.k-auto-scrollable, #gridConUpViewCustomHistory .k-grid-content.k-auto-scrollable {
        height: 280px !important;
    }
</style>
@{
    ViewBag.Title = "Uploader";
}


<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <section class="col-sm-12 connectedSortable" style="display:inherit; min-height:480px">
                <div id="pmviewhistorymain" style="display:none;" class="col-lg-12 card direct-chat direct-chat-primary">


                    <div class="row" style="margin:10px">


                        <div class="col-10">
                            <div class="menuName">
                                <div><span id="inputdishname1"> </span></div>
                                <div style="height:20px;display: inline-grid;margin-top: -1px;margin-left: 2px;color: #000;">
                                    <label class="form-label-consultant-uploader" style="font-size:0.965em!important" id="historytext">
                                        Batch Failed, Following records have the invalid/incorrect data. Refer below list and correct the data in excel and re-upload.
                                    </label>
                                </div>
                            </div>
                        </div>
                        <!--</div>-->
                        <div class="col-2" style="margin-top: 10px; text-align: right;padding-right:8px;">
                            @*<button type="submit" id="APLMOGbtnback" onclick="back()" class="btn btn-success btn-xs">Back</button>
                                <button type="submit" id="ALLBATCHVIEW" onclick="AllViewBatch()" class="btn btn-success btn-xs">View All Batch(s)</button>*@
                            <button type="submit" id="Pmbtnback" class="btn btn-success btn-xs">Back</button>
                            <button type="submit" id="ALLBATCHVIEW" class="btn btn-success btn-xs">View All Batch(s)</button>
                        </div>


                    </div>

                    @*<div class="row" style="margin-top:10px">
                            <div class="col-12">

                                <div id="gridPMViewCustomHistoryDetails" style="max-height: 200px;margin-top: 24px;"></div>
                            </div>

                        </div>
                        <div class="row" style="margin-top:10px!important">


                        </div>*@



                <div class="row" style="margin-top:10px">
                    <span style="float:left; margin-top:2px!important" id="batchsearch">
                        <input type="text" id="BatchmyInput" placeholder="Search" class="search-input" title="Start typing to filter" style="margin-right:9px;margin-bottom: 5px;">
                        <i class="fas fa-search" style="position: relative; right: -92%;top: 4px;font-size: 0.7em;color: #76b4b0;"></i>
                    </span>
                    <div class="col-12">

                        <div id="gridConUpViewCustomHistory"></div>
                    </div>

                </div>
                    <div class="row" style="margin-top:10px">
                        
                                <span style="float:left; margin-top:2px!important;display:none;" id="BATCHWISEearch">
                                    <input type="text" id="BATCHWISEmyInput" placeholder="Search" class="search-input" title="Start typing to filter" style="margin-right:9px;margin-bottom: 5px;">
                                    <i class="fas fa-search" style="position: relative; right: -92%;top: 4px;font-size: 0.7em;color: #76b4b0;"></i>
                                </span>
                            
                        <div class="col-12">
                            @*<div id="gridRecipeCustom" style="max-height:200px;"></div>*@
                            <div id="GETALLPmViewALLHistoryBATCHWISE"></div>
                        </div>

                    </div>



                </div>
                <div id="PMMaster" class="col-lg-12 card direct-chat direct-chat-primary">
                    <div class="card-header">

                        <div class="card-tools" style="margin-top: -6px;">
                            @*<button id="btnExport" type="submit" class="btn btn-tool" data-toggle="tooltip" title=""
                                        data-widget="chat-pane-toggle" style="padding-top:7px">
                                    Export To Excel
                                </button>*@
                            <span style="float:left">
                                <input type="text" style=" margin-top: 8px;" id="myInput" placeholder="Search" class="search-input" title="Start typing to filter">
                                <i class="fas fa-search" style="position: relative; right: -277px;top: 7px;font-size: 0.8em;color: #76b4b0;"></i>
                            </span>
                            @*<button id="InitiateBulkChanges" type="submit" class="btn btn-tool" data-toggle="tooltip" title=""
                                        data-widget="chat-pane-toggle" style="padding-top:7px; display:none;">
                                    Apply Bulk Changes
                                </button>
                                <button id="CancelBulkChanges" type="submit" class="btn btn-tool" data-toggle="tooltip" title=""
                                        data-widget="chat-pane-toggle" style="display:none;padding-top:7px; display:none;">
                                    Cancel Bulk Changes
                                </button>
                                <button id="SaveBulkChanges" type="submit" class="btn btn-success-bulk btn-xs" data-toggle="tooltip" title=""
                                        data-widget="chat-pane-toggle" style="display:none; margin-top:5px">
                                    Save Bulk Changes
                                </button>*@


                            @*<a href="MOG/DownloadExcTemplate/" target="_blank" class="btn btn-tool" style="margin-top:20px;"> Export To Template</a>*@
                            @*<button id="btnExport" type="submit" class="btn btn-tool" data-toggle="tooltip" title=""
                                        data-widget="chat-pane-toggle" style="padding-top:7px">
                                    Export To Excel
                                </button>*@

                            <button id="BtnExportTemp" type="submit" class="btn btn-tool" data-toggle="tooltip" title=""
                                    data-widget="chat-pane-toggle" style="padding-top:7px">
                                Download Template
                            </button>
                            <button id="Btnviewuploadhistory" type="submit" class="btn btn-tool" data-toggle="tooltip" title=""
                                    data-widget="chat-pane-toggle" style="padding-top:7px">
                                View Upload History
                            </button>
                            @*<span style="float:left">
                                    <input type="text" style=" margin-top: 8px;" id="myInput" placeholder="Search" class="search-input" title="Start typing to filter">
                                    <i class="fas fa-search" style="position: relative; right: -277px;top: 7px;font-size: 0.8em;color: #76b4b0;"></i>
                                </span>*@
                            <div style="float:left;margin-top: 8px;">
                                <div id="ddTemplate"></div>
                            </div>
                            <button id="ExcelUpload" type="submit" class="btn btn-success btn-xs" data-toggle="tooltip" title=""
                                    data-widget="chat-pane-toggle" style="margin-top:5px; ">
                                Upload Template
                            </button>



                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div id="fpbody" class="card-body">
                        <div id="gridConsultantUploader"></div>

                        <div id="UploadExcelFile">

                            <div class="container">
                                @*<div class="row">
                                        <div class="col-4">
                                            <div id="ddTemplate1"></div>
                                        </div>
                                    </div>*@
                                <div class="row">
                                    <div class="form-control-label" style="padding-top:-2px;margin-left:8px;margin-bottom:0px!important;" id="uploaderText"> Please select a template to upload</div>
                                </div>

                                <div class="row">
                                    <div class="col-4" id="EXclpmCodeDiv" style="min-width:85px!important">
                                        <input type="file" id="file" class="form-control-file" accept=".xlsx,.xls,.json,.csv" style="font-size:0.8em" />
                                    </div>
                                </div>
                                <div class="row" style="float:left;">
                                    <div class="col-11">
                                        <button id="UploadPmExcel" type="submit" class="btn btn-success btn-xs" data-toggle="tooltip" title=""
                                                data-widget="chat-pane-toggle" style="margin-top:5px; ">
                                            Upload File
                                        </button>
                                    </div>


                                </div>

                            </div>


                        </div>

                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                    </div>
                    <!-- /.card-footer-->
                </div>
            </section>
            <!-- /.Left col -->
        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<!--<section class="content">
    <div class="container-fluid">-->
<!-- Main row -->
<!--<div class="row">-->
<!-- Left col -->
<!--<section class="col-sm-12 connectedSortable" style="display:inherit; min-height:480px">



    <div id="PMMaster">-->
<!-- /.card-header -->
<!--<div id="fpbody" class="col-lg-12 card direct-chat direct-chat-primary">



</div>-->
<!-- /.card-body -->
<!-- /.card-footer-->
<!--</div>
</section>-->
<!-- /.Left col -->
<!--</div>-->
<!-- /.row (main row) -->
<!--</div>--><!-- /.container-fluid -->
<!--</section>-->

PresentationLayer/HRIS.MvcApp/Views/HRISMaster/CostCenter.cshtml
<script>

    var HRISMasters = {
        GetLoginUserDetailsUrl: "@Url.Action("GetLoginUserDetails", "HRISMaster")",
        GetCostCenterDataList: "@Url.Action("GetCostCenterMasterDataList", "Employee")",
        SaveCostCenterData: "@Url.Action("SaveCostCenterData", "HRISMaster")",
    }
</script>
<script src="~/Scripts/CookBook/CostCenter.js"></script>
<style>
    .popover {
        z-index: 120000 !important;
    }

    .k-window {
        height: 140px !important;
    }

    .slider {
        top: 6px !important;
        bottom: -6px !important;
    }
</style>
@{
    ViewBag.Title = "Cost Center";
}

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <section class="col-sm-12 connectedSortable" style="display:inherit; min-height:480px">
                <div id="ColorMaster" class="col-lg-12 card direct-chat direct-chat-primary">
                    <div class="card-header">

                        <h3 class="card-title" style="margin-left: -17px;"></h3>
                        <div class="card-tools" style="margin-top: -6px;width: 715px;">
                            <span style="float:left" class="costcenterdetailsearch">
                                <input type="text" id="myInput" placeholder="Search" class="search-input" style="position: relative; padding-left: 25px; height: 25px !important;">
                                <i class="fas fa-search" style="position: relative; left: 20px; font-size: 0.8em; color: #76b4b0; z-index: 1; top: 5px !important; opacity: 1;"></i>
                            </span>
                            <div class="float-right">
                                <button id="btnExport" type="submit" class="btn btn-tool" data-toggle="tooltip" title=""
                                        data-widget="chat-pane-toggle" style="padding-top:7px">
                                    Export To Excel
                                </button>
                                <button id="AddNew" type="submit" class="btn btn-success btn-xs" data-toggle="tooltip" title=""
                                        data-widget="chat-pane-toggle" style="margin-top:5px">
                                    Add New Cost Center
                                </button>
                            </div>

                        </div>
                    </div>
                    <div id="costcenterid" style="display:none;"></div>
                    <!-- /.card-header -->
                    <div id="clbody" class="card-body">
                        <div id="bulkerror" class="alert alert-danger alert-dismissible" style="display:none">
                            <i class="icon fas fa-exclamation"></i>
                            <p style="font-size: 12px;margin-bottom: .15rem;margin-left: 5px;">
                            </p>
                        </div>
                        <div id="success" class="alert alert-success alert-dismissible" style="display:none">
                            <i class="icon fas fa-check"></i>
                            <p style="font-size: 12px;margin-bottom: .15rem;margin-left: 5px;">
                            </p>
                        </div>
                        <div id="gridCostCenter"></div>
                        <div id="windowEdit">
                            <div class="container">
                                <div id="error" class="alert alert-danger alert-dismissible" style="display:none">
                                    <i class="icon fas fa-exclamation"></i>
                                    <p style="font-size: 12px;margin-bottom: .15rem;margin-left: 5px;">
                                    </p>
                                </div>
                                <div class="row">

                                    <div class="col-6">
                                        <label class="form-control-label">Cost Center<span class="mandatoryAsterisk">*</span></label>
                                        <input type="text" id="costcentername" class="form-control" />
                                    </div>
                                    <div class="col-12" style="display:block">
                                        <label class="form-control-label">Remark</label>
                                        <input type="text" id="remark" class="form-control" />
                                    </div>


                                </div>
                                <div class="row" style="margin-top:10px !important;">
                                    <div class="modal-footer col" style="padding-right:7.5px!important; align-items:flex-end!important">
                                        <button type="submit" id="btnCancel" class="btn btn-tool">Cancel</button>
                                        <button type="submit" id="btnSubmit" class="btn btn-info">Save</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                    </div>
                    <!-- /.card-footer-->
                </div>
            </section>
            <!-- /.Left col -->
        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>